ceres-solver: Disable Metis due to build error
Error was:

  | MetisSupport.h:112:34: error: cannot convert 'int*' to 'idx_t*' {aka 'long int*'}
  |   112 |      output_error = METIS_NodeND(&m, m_indexPtr.data(), m_innerIndices.data(), NULL, NULL, perm.data(), iperm.data());
  |       |                                  ^~
  |       |                                  |
  |       |                                  int*