protobuf-c: Update from v1.3.1 to v1.3.2 to fix grpc build error
Error was:

  | channelz_service.cc: In function ‘grpc::protobuf::util::Status grpc::ParseJson(const char*, grpc::protobuf::Message*)’:
  | channelz_service.cc:30:11: error: ‘struct google::protobuf::util::JsonParseOptions’ has no member named ‘case_insensitive_enum_parsing’
  |    30 |   options.case_insensitive_enum_parsing = true;
  |       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~