bpftool.bb: Disable SECURITY_CFLAGS
We do not pass CFLAGS to build and fortify sources needs some
optimization to be enabled, its better to reset the additional flags and
let the build system add them as it needs

Fixes build failures like
tools/include/tools/libc_compat.h:11:21: error: static declaration of 'reallocarray' follows non-static declaration
|    11 | static inline void *reallocarray(void *ptr, size_t nmemb, size_t size)
|       |                     ^~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit d46e1e767f6b91dc25935e0c48d9d362dd50d879)
Signed-off-by: Armin Kuster <akuster808@gmail.com>