python-protobuf: Update from v3.6.1 to v3.9.2 to fix build error
Error was:

  | In file included from google/protobuf/pyext/descriptor_pool.cc:38:
  | ./google/protobuf/pyext/descriptor_pool.h:80:3: error: 'hash_map' does not name a type; did you mean 'hash'?
  |    hash_map<const void*, PyObject*>* descriptor_options;
  |    ^~~~~~~~
  |    hash