redis: Fix build with clang/x86
Need to link with libatomics for 64bit atomics support
Fixes
i686-yoe-linux/i686-yoe-linux-ld: networking.o: in function `createClient':
| /usr/src/debug/redis/4.0.14-r0/redis-4.0.14/src/networking.c:103: undefined reference to `__atomic_fetch_add_8'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 2b49254d61ca817799a206cd022617854aa5bc0b)
Signed-off-by: Armin Kuster <akuster808@gmail.com>